"use client"

import { useState } from "react"
import { pdf, Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer"
import { Button } from "@/components/ui/button"
import { FileText, Loader2 } from "lucide-react"
import { toast } from "sonner"

const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 10, fontFamily: "Helvetica" },
  header: { marginBottom: 20 },
  title: { fontSize: 18, fontWeight: "bold" },
  subtitle: { fontSize: 10, color: "#666", marginTop: 4 },
  statsRow: { flexDirection: "row", gap: 10, marginBottom: 16 },
  statBox: { flex: 1, border: "1px solid #ddd", padding: 8, borderRadius: 4 },
  statLabel: { fontSize: 8, color: "#666", marginBottom: 2 },
  statValue: { fontSize: 14, fontWeight: "bold" },
  tableHeader: { flexDirection: "row", borderBottom: "2px solid #333", paddingVertical: 6, marginTop: 8 },
  tableHeaderText: { flex: 1, fontWeight: "bold", fontSize: 8 },
  tableRow: { flexDirection: "row", borderBottom: "1px solid #eee", paddingVertical: 4 },
  tableRowAlt: { flexDirection: "row", borderBottom: "1px solid #eee", paddingVertical: 4, backgroundColor: "#f9f9f9" },
  tableCell: { flex: 1, fontSize: 8 },
  footer: { position: "absolute", bottom: 20, left: 30, right: 30, fontSize: 8, color: "#999", textAlign: "center" },
})

function formatUGX(amount: number) {
  return `UGX ${(amount / 100).toLocaleString()}`
}

function formatDate(date: any) {
  if (!date) return "\u2014"
  return new Date(date).toLocaleDateString()
}

export function LoanPdfReport({ loans, stats, filteredCount, totalCount }: { loans: any[]; stats: any; filteredCount: number; totalCount: number }) {
  const [loading, setLoading] = useState(false)

  const handleExport = async () => {
    setLoading(true)
    try {
      const totalDisbursed = loans.reduce((s, l) => s + (l.amount || 0), 0)
      const outstanding = loans.reduce((s, l) => s + (l.balance || 0), 0)

      const blob = await pdf(
        <Document>
          <Page size="A4" style={styles.page}>
            <View style={styles.header}>
              <Text style={styles.title}>Loans Report</Text>
              <Text style={styles.subtitle}>Generated {new Date().toLocaleDateString()} · {filteredCount} of {totalCount} loans shown</Text>
            </View>

            <View style={styles.statsRow}>
              <View style={styles.statBox}>
                <Text style={styles.statLabel}>Total Disbursed</Text>
                <Text style={styles.statValue}>{formatUGX(totalDisbursed)}</Text>
              </View>
              <View style={styles.statBox}>
                <Text style={styles.statLabel}>Outstanding</Text>
                <Text style={styles.statValue}>{formatUGX(outstanding)}</Text>
              </View>
              <View style={styles.statBox}>
                <Text style={styles.statLabel}>Active</Text>
                <Text style={styles.statValue}>{loans.filter((l) => l.status === "active").length}</Text>
              </View>
              <View style={styles.statBox}>
                <Text style={styles.statLabel}>Settled</Text>
                <Text style={styles.statValue}>{loans.filter((l) => l.status === "settled").length}</Text>
              </View>
            </View>

            <View style={styles.tableHeader}>
              <Text style={styles.tableHeaderText}>Ref</Text>
              <Text style={styles.tableHeaderText}>Member</Text>
              <Text style={styles.tableHeaderText}>Amount</Text>
              <Text style={styles.tableHeaderText}>Paid</Text>
              <Text style={styles.tableHeaderText}>Balance</Text>
              <Text style={styles.tableHeaderText}>Status</Text>
              <Text style={styles.tableHeaderText}>Due</Text>
            </View>
            {loans.map((l, i) => {
              const paid = Math.max(0, (l.expectedReceived || 0) - (l.balance || 0))
              return (
                <View key={l.id} style={i % 2 === 0 ? styles.tableRow : styles.tableRowAlt}>
                  <Text style={styles.tableCell}>{l.loanRef ?? "\u2014"}</Text>
                  <Text style={styles.tableCell}>{l.memberName ?? "\u2014"}</Text>
                  <Text style={styles.tableCell}>{formatUGX(l.amount || 0)}</Text>
                  <Text style={styles.tableCell}>{formatUGX(paid)}</Text>
                  <Text style={styles.tableCell}>{formatUGX(l.balance || 0)}</Text>
                  <Text style={styles.tableCell}>{l.status ?? "\u2014"}</Text>
                  <Text style={styles.tableCell}>{formatDate(l.dueDate)}</Text>
                </View>
              )
            })}

            <Text style={styles.footer}>Generated by SACCO Management System</Text>
          </Page>
        </Document>
      ).toBlob()

      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `loans-report-${new Date().toISOString().split("T")[0]}.pdf`
      a.click()
      URL.revokeObjectURL(url)
      toast.success("Loans report exported to PDF")
    } catch (err) {
      console.error(err)
      toast.error("Failed to generate PDF")
    } finally {
      setLoading(false)
    }
  }

  return (
    <Button variant="outline" size="sm" onClick={handleExport} disabled={loading}>
      {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileText className="mr-2 h-4 w-4" />}
      PDF
    </Button>
  )
}
